language: csharp
sudo: required
dist: trusty
solution: FluentRestBuilder.sln
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: latest
dotnet: 1.0.1
os:  
  - linux
  - osx
branches:  
  only:
    - master
    - dev
    - /^feature\/.*$/
    - /^release\/.*$/
    - /^hotfix\/.*$/
script:
  - sed -i 's/net452;//g' *.csproj
  - dotnet restore
  - dotnet build
  - find ./test/ -iname "*.Test.csproj" -execdir dotnet test \;
  - find ./src/ -iname "*.csproj" -execdir dotnet pack -c Release --version-suffix="ci-$TRAVIS_BUILD_NUMBER" \;
