language: csharp
mono: none
dist: trusty
osx_image: xcode8.1
solution: FluentRestBuilder.sln
dotnet: 2.0.0
os:  
  - linux
  - osx
branches:  
  only:
    - master
    - dev
    - /^feature\/.*$/
    - /^release\/.*$/
    - /^hotfix\/.*$/
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      rvm install ruby-2.3.3;
      rvm --default use 2.3.3;
    fi
script:
  - dotnet build
  - ./test.sh
  - dotnet pack -c Release --version-suffix="ci"
