language: csharp
sudo: required
dist: trusty
dotnet: 1.0.0-preview2-003131
env:  
  - CLI_VERSION=latest
addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
mono:
  - 4.2.3
os:  
  - linux
  - osx
branches:  
  only:
    - master
    - dev
    - /^feature\/.*$/
    - /^release\/.*$/
    - /^hotfix\/.*$/
before_install:  
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; mkdir -p /usr/local/lib; fi
script:
  - ./build.sh
