language: csharp
dist: trusty
solution: FluentRestBuilder.sln
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
dotnet: 1.0.1
os:  
  - linux
  - osx
branches:  
  only:
    - master
    - dev
    - /^feature\/.*$/
    - /^release\/.*$/
    - /^hotfix\/.*$/
script:
  - find . -type f -name '*.csproj' -exec sed -i.bak 's/net452;//' {} +
  - sed -e 's/Id="SA1633" Action="Error"/Id="SA1633" Action="Hidden"/' -i.bak FluentRestBuilder.ruleset
  - sed -e 's/Id="SA1412" Action="Warning"/Id="SA1412" Action="Hidden"/' -i.bak FluentRestBuilder.ruleset
  - dotnet restore
  - dotnet build
  - find ./test/ -iname "*.Test.csproj" -exec dotnet test {} \;
  - find ./src/ -iname "*.csproj" -exec dotnet pack {} -c Release --version-suffix="ci" \;
