language: csharp
mono: none
dist: trusty
solution: FluentRestBuilder.sln
dotnet: 2.0.0
os:  
  - linux
  - osx
branches:  
  only:
    - master
    - dev
    - /^feature\/.*$/
    - /^release\/.*$/
    - /^hotfix\/.*$/
script:
  - dotnet build
  - ./test.sh
  - dotnet pack -c Release --version-suffix="ci"
