language: csharp
dist: trusty
solution: FluentRestBuilder.sln
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
dotnet: 1.0.1
os:  
  - linux
  - osx
branches:  
  only:
    - master
    - dev
    - /^feature\/.*$/
    - /^release\/.*$/
    - /^hotfix\/.*$/
script:
  - ./patch.sh
  - dotnet restore
  - dotnet build
  - ./test.sh
  - ./pack.sh
