version: '{build}'
branches:
  only:
    - master
    - dev
    - /feature\/.*/
    - /release\/.*/
    - /hotfix\/.*/
image: Visual Studio 2017
before_build:
  - cmd: dotnet restore
test_script:
  - cmd: .\test.cmd
before_package:
  - cmd: .\pack.cmd
matrix:
  fast_finish: true
nuget:
  disable_publish_on_pr: true
configuration:
  - Debug
  - Release
artifacts:
  - path: src\**\bin\$(configuration)\*.nupkg
    name: NuGet
pull_requests:
  do_not_increment_build_number: true
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/fluentrestbuilder-ci/api/v2/package
    api_key:
      secure: 5Nf/5WDJ5K0rIMMTMh+sSnN3TdkILOQFgODchMX+g6s1CxHTXFhvkqu3IGkQDND3
    skip_symbols: true
    on:
      branch: dev
      configuration: Debug
  - provider: NuGet
    name: production
    api_key:
      secure: 5kUNwZ79j5lXOZtxjSUMmoe5MwtVVi89YP3zK+m49rWk0MCGCL//bh06o2IJAUeh
    on:
      appveyor_repo_tag: true
      configuration: Release